// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(public)/t/[tableId]/done/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/t/[tableId]/done">> = Specific
  const handler = {} as typeof import("../../app/(public)/t/[tableId]/done/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/t/[tableId]/order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/t/[tableId]/order">> = Specific
  const handler = {} as typeof import("../../app/(public)/t/[tableId]/order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/t/[tableId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/t/[tableId]">> = Specific
  const handler = {} as typeof import("../../app/(public)/t/[tableId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/t/[tableId]/pay/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/t/[tableId]/pay">> = Specific
  const handler = {} as typeof import("../../app/(public)/t/[tableId]/pay/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(staff)/staff/(protected)/admin/config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/admin/config">> = Specific
  const handler = {} as typeof import("../../app/(staff)/staff/(protected)/admin/config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(staff)/staff/(protected)/admin/menu/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/admin/menu/categories">> = Specific
  const handler = {} as typeof import("../../app/(staff)/staff/(protected)/admin/menu/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(staff)/staff/(protected)/admin/menu/items/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/admin/menu/items">> = Specific
  const handler = {} as typeof import("../../app/(staff)/staff/(protected)/admin/menu/items/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(staff)/staff/(protected)/admin/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/admin/menu">> = Specific
  const handler = {} as typeof import("../../app/(staff)/staff/(protected)/admin/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(staff)/staff/(protected)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/admin">> = Specific
  const handler = {} as typeof import("../../app/(staff)/staff/(protected)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(staff)/staff/(protected)/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/admin/reports">> = Specific
  const handler = {} as typeof import("../../app/(staff)/staff/(protected)/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(staff)/staff/(protected)/admin/tables/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/admin/tables">> = Specific
  const handler = {} as typeof import("../../app/(staff)/staff/(protected)/admin/tables/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(staff)/staff/(protected)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/admin/users">> = Specific
  const handler = {} as typeof import("../../app/(staff)/staff/(protected)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(staff)/staff/(protected)/bar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/bar">> = Specific
  const handler = {} as typeof import("../../app/(staff)/staff/(protected)/bar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(staff)/staff/(protected)/cashier/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/cashier">> = Specific
  const handler = {} as typeof import("../../app/(staff)/staff/(protected)/cashier/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(staff)/staff/(protected)/kitchen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/kitchen">> = Specific
  const handler = {} as typeof import("../../app/(staff)/staff/(protected)/kitchen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(staff)/staff/(protected)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff">> = Specific
  const handler = {} as typeof import("../../app/(staff)/staff/(protected)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(staff)/staff/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/login">> = Specific
  const handler = {} as typeof import("../../app/(staff)/staff/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/diner/order/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/diner/order/confirm">> = Specific
  const handler = {} as typeof import("../../app/api/diner/order/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/diner/order/items/[itemId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/diner/order/items/[itemId]">> = Specific
  const handler = {} as typeof import("../../app/api/diner/order/items/[itemId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/diner/order/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/diner/order/items">> = Specific
  const handler = {} as typeof import("../../app/api/diner/order/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/diner/order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/diner/order">> = Specific
  const handler = {} as typeof import("../../app/api/diner/order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/diner/payment/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/diner/payment/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/diner/payment/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/diner/session/clear/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/diner/session/clear">> = Specific
  const handler = {} as typeof import("../../app/api/diner/session/clear/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/diner/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/diner/session">> = Specific
  const handler = {} as typeof import("../../app/api/diner/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/admin/categories/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/admin/categories/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/staff/admin/categories/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/admin/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/admin/categories">> = Specific
  const handler = {} as typeof import("../../app/api/staff/admin/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/admin/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/admin/config">> = Specific
  const handler = {} as typeof import("../../app/api/staff/admin/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/admin/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../app/api/staff/admin/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/admin/menu-items/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/admin/menu-items/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/staff/admin/menu-items/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/admin/menu-items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/admin/menu-items">> = Specific
  const handler = {} as typeof import("../../app/api/staff/admin/menu-items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/admin/reports/prep-time/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/admin/reports/prep-time">> = Specific
  const handler = {} as typeof import("../../app/api/staff/admin/reports/prep-time/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/admin/reports/sales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/admin/reports/sales">> = Specific
  const handler = {} as typeof import("../../app/api/staff/admin/reports/sales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/admin/reports/top-items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/admin/reports/top-items">> = Specific
  const handler = {} as typeof import("../../app/api/staff/admin/reports/top-items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/admin/tables/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/admin/tables/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/staff/admin/tables/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/admin/tables/positions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/admin/tables/positions">> = Specific
  const handler = {} as typeof import("../../app/api/staff/admin/tables/positions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/admin/tables/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/admin/tables">> = Specific
  const handler = {} as typeof import("../../app/api/staff/admin/tables/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/staff/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/admin/users">> = Specific
  const handler = {} as typeof import("../../app/api/staff/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/bar/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/bar/items">> = Specific
  const handler = {} as typeof import("../../app/api/staff/bar/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/kitchen/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/kitchen/items">> = Specific
  const handler = {} as typeof import("../../app/api/staff/kitchen/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/orders/items/[itemId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/orders/items/[itemId]">> = Specific
  const handler = {} as typeof import("../../app/api/staff/orders/items/[itemId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/tables/[tableId]/close/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/tables/[tableId]/close">> = Specific
  const handler = {} as typeof import("../../app/api/staff/tables/[tableId]/close/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/tables/[tableId]/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/tables/[tableId]/items">> = Specific
  const handler = {} as typeof import("../../app/api/staff/tables/[tableId]/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/tables/[tableId]/mark-paid-offline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/tables/[tableId]/mark-paid-offline">> = Specific
  const handler = {} as typeof import("../../app/api/staff/tables/[tableId]/mark-paid-offline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/tables/[tableId]/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/tables/[tableId]/reset">> = Specific
  const handler = {} as typeof import("../../app/api/staff/tables/[tableId]/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/tables/[tableId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/tables/[tableId]">> = Specific
  const handler = {} as typeof import("../../app/api/staff/tables/[tableId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/tables/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/tables">> = Specific
  const handler = {} as typeof import("../../app/api/staff/tables/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/mercadopago/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/mercadopago">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/mercadopago/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(staff)/staff/(protected)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/staff">> = Specific
  const handler = {} as typeof import("../../app/(staff)/staff/(protected)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
