// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/staff" | "/staff/admin" | "/staff/admin/config" | "/staff/admin/menu" | "/staff/admin/menu/categories" | "/staff/admin/menu/items" | "/staff/admin/reports" | "/staff/admin/tables" | "/staff/admin/users" | "/staff/bar" | "/staff/cashier" | "/staff/kitchen" | "/staff/login" | "/t/[tableId]" | "/t/[tableId]/done" | "/t/[tableId]/order" | "/t/[tableId]/pay"
type AppRouteHandlerRoutes = "/api/diner/order" | "/api/diner/order/confirm" | "/api/diner/order/items" | "/api/diner/order/items/[itemId]" | "/api/diner/payment/checkout" | "/api/diner/session" | "/api/diner/session/clear" | "/api/staff/admin/categories" | "/api/staff/admin/categories/[id]" | "/api/staff/admin/config" | "/api/staff/admin/dashboard" | "/api/staff/admin/menu-items" | "/api/staff/admin/menu-items/[id]" | "/api/staff/admin/reports/prep-time" | "/api/staff/admin/reports/sales" | "/api/staff/admin/reports/top-items" | "/api/staff/admin/tables" | "/api/staff/admin/tables/[id]" | "/api/staff/admin/tables/positions" | "/api/staff/admin/users" | "/api/staff/admin/users/[id]" | "/api/staff/bar/items" | "/api/staff/kitchen/items" | "/api/staff/orders/items/[itemId]" | "/api/staff/tables" | "/api/staff/tables/[tableId]" | "/api/staff/tables/[tableId]/close" | "/api/staff/tables/[tableId]/items" | "/api/staff/tables/[tableId]/mark-paid-offline" | "/api/staff/tables/[tableId]/reset" | "/api/webhooks/mercadopago"
type PageRoutes = never
type LayoutRoutes = "/" | "/staff"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/diner/order": {}
  "/api/diner/order/confirm": {}
  "/api/diner/order/items": {}
  "/api/diner/order/items/[itemId]": { "itemId": string; }
  "/api/diner/payment/checkout": {}
  "/api/diner/session": {}
  "/api/diner/session/clear": {}
  "/api/staff/admin/categories": {}
  "/api/staff/admin/categories/[id]": { "id": string; }
  "/api/staff/admin/config": {}
  "/api/staff/admin/dashboard": {}
  "/api/staff/admin/menu-items": {}
  "/api/staff/admin/menu-items/[id]": { "id": string; }
  "/api/staff/admin/reports/prep-time": {}
  "/api/staff/admin/reports/sales": {}
  "/api/staff/admin/reports/top-items": {}
  "/api/staff/admin/tables": {}
  "/api/staff/admin/tables/[id]": { "id": string; }
  "/api/staff/admin/tables/positions": {}
  "/api/staff/admin/users": {}
  "/api/staff/admin/users/[id]": { "id": string; }
  "/api/staff/bar/items": {}
  "/api/staff/kitchen/items": {}
  "/api/staff/orders/items/[itemId]": { "itemId": string; }
  "/api/staff/tables": {}
  "/api/staff/tables/[tableId]": { "tableId": string; }
  "/api/staff/tables/[tableId]/close": { "tableId": string; }
  "/api/staff/tables/[tableId]/items": { "tableId": string; }
  "/api/staff/tables/[tableId]/mark-paid-offline": { "tableId": string; }
  "/api/staff/tables/[tableId]/reset": { "tableId": string; }
  "/api/webhooks/mercadopago": {}
  "/staff": {}
  "/staff/admin": {}
  "/staff/admin/config": {}
  "/staff/admin/menu": {}
  "/staff/admin/menu/categories": {}
  "/staff/admin/menu/items": {}
  "/staff/admin/reports": {}
  "/staff/admin/tables": {}
  "/staff/admin/users": {}
  "/staff/bar": {}
  "/staff/cashier": {}
  "/staff/kitchen": {}
  "/staff/login": {}
  "/t/[tableId]": { "tableId": string; }
  "/t/[tableId]/done": { "tableId": string; }
  "/t/[tableId]/order": { "tableId": string; }
  "/t/[tableId]/pay": { "tableId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/staff": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
